# SPDX-FileCopyrightText: 2020 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: example.infra.tf-config
  namespace: default
data:
  main.tf: |
    provider "aws" {
      access_key = var.ACCESS_KEY_ID
      secret_key = var.SECRET_ACCESS_KEY
      region     = "eu-central-1"
    }

    resource "aws_route53_record" "www" {
      zone_id = "Z3ABCDE5FGHIJK"
      name    = "subdomain.example.com"
      ttl     = "120"
      type    = "A"
      records = ["1.2.3.4"]
    }
  variables.tf: |
    variable "ACCESS_KEY_ID" {
      description = "AWS Access Key ID of technical user"
      type        = string
    }

    variable "SECRET_ACCESS_KEY" {
      description = "AWS Secret Access Key of technical user"
      type        = string
    }

---
apiVersion: v1
kind: Secret
metadata:
  name: example.infra.tf-vars
  namespace: default
type: Opaque
stringData:
  terraform.tfvars: |
    ACCESS_KEY_ID = "AAAAAAAAAAAAAAAAAAAA"
    SECRET_ACCESS_KEY = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
