# SPDX-FileCopyrightText: 2020 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: v1
kind: Pod
metadata:
  name: example.infra.tf-apply
  namespace: default
spec:
  activeDeadlineSeconds: 1800
  containers:
  - name: terraformer
    image: eu.gcr.io/gardener-project/gardener/terraformer:v2.1.0-dev-576acc71b0716bc0c7c431cb607163d5cd8aae9b-dirty
    imagePullPolicy: IfNotPresent
#    command:
#    - /terraformer
#    - apply
#    - --zap-log-level=debug
#    - --configuration-configmap-name=example.infra.tf-config
#    - --state-configmap-name=example.infra.tf-state
#    - --variables-secret-name=example.infra.tf-vars
    command:
      - sh
      - -c
      - "while true; do sleep 2; done"
    resources:
      requests:
        cpu: 100m
    securityContext:
      runAsUser: 1001
  restartPolicy: Never
  serviceAccountName: terraformer
  terminationGracePeriodSeconds: 600
